import { Toaster } from "sonner";
import type { Metadata } from "next";

import { ReactQueryProvider } from "@/providers/react-query-provider";
import { LoggedUserProvider } from "@/providers/logged-user-provider";
import { CartProvider } from "@/providers/cart-provider";

import "./globals.css";

export const metadata: Metadata = {
  title: "Nowaste",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ReactQueryProvider>
          <LoggedUserProvider>
            <CartProvider>
              <main>{children}</main>
              <Toaster richColors />
            </CartProvider>
          </LoggedUserProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
